### ISSUE TITLE
Implement "Partners / v1" block

### ISSUE THREAD

**Issue by liliya-trofimova** [rolling-scopes/rs-site#13]
# Description
Implement "Partners / v1" block

# Steps

1. Go to [designs ](https://www.figma.com/file/RefMpMk3zyw8efZ8UGOkYM/Prototyping?node-id=836%3A169792) and find "Partners / v1" block
2. Implement the block

**Comment by oleksiisydorenko1** [comment]
@liliya-trofimova Please add more details about partners. I mean should we add extra field priority for partners?

**Comment by oleksiisydorenko1** [comment]
https://github.com/rolling-scopes/rs-site/pull/38
