### ISSUE TITLE
Implement Social networks RUS / v1

### ISSUE THREAD

**Issue by Irencha** [rolling-scopes/rs-site#17]
# Description
Implement "Social networks RUS / v1" block

# Steps

1. Go to [designs ](https://www.figma.com/file/RefMpMk3zyw8efZ8UGOkYM/Prototyping?node-id=882%3A175357)and find "Social networks RUS / v1" block
2. Implement the block

**Comment by oleksiisydorenko1** [comment]
If there are not many options, which means only one option, the button or link should redirect directly to the resource (without opening modal)
