### ISSUE TITLE
Configure aliases and routing for entities

### ISSUE THREAD

**Issue by oleksiisydorenko1** [rolling-scopes/rs-site#18]
# Description
It's good to use some kind of shortcut for imports, just compare how it looks better in comparison with "../../../ import hell"

// Before
```
import Button from "./form/Button" 
import { Layout } from '../../Components/Layout'
```

// After
```
import Button from "@/form/Button"
import { Layout } from '@Components/Layout'
```

# Problems

1. Need to create a mechanism for alliases
2. Need to create single file for each group of items (ex. components, utils)

# Steps

1. Configure aliases 
2. Go to [guide](https://bobbyhadz.com/blog/react-export-multiple-components) and setup a common approach

**Comment by aleksKudr** [comment]
Done in 
https://github.com/oleksiisydorenko1/cms-sanity/commit/6d1e639fc63799315586cb38a6dcad1082f7006b
