### ISSUE TITLE
Implement RS School Alumni block / Community main page

### ISSUE THREAD

**Issue by liliya-trofimova** [rolling-scopes/rs-site#39]
# Description
Implement RS School Alumni block / Community main page block

# Steps

1. Go to [design](https://www.figma.com/file/RefMpMk3zyw8efZ8UGOkYM/Prototyping?node-id=2144%3A268617&t=fc1XykM9GR3DeUjy-4) and find "RS School Alumni 3 rows / Community main page / temporary version" frame 
2. Read blue notes 
3. The most important option is to select the order of logos in the admin area 
4. You can find all logotypes in svg format [here](https://drive.google.com/drive/folders/1QlDhKfXI1B7fpQPBZOuYqmv3o-uexIHs?usp=share_link)
5. Implement this block

**Comment by liliya-trofimova** [comment]
This website has an interesting variant of logo block animation https://centra.com/

**Comment by oleksiisydorenko1** [comment]
[pr](https://github.com/rolling-scopes/rs-site/pull/45)
